#!/usr/bin/env ruby

require 'ansible_make_role.rb'
require "shellopts"

USAGE = "f,force v,verbose version r,roles-dir=DIR G,no-git-ignore -- MAKE-ROLES-DIRECTORY"

force = false
verbose = false
roles_dir = nil
git_ignore = true

args = ShellOpts.process(USAGE, ARGV) { |opt, arg|
  case opt
    when '-f', '--force'; force = true
    when '-v', '--verbose'; verbose = true
    when '--version'; puts "ansible-make-role #{AnsibleMakeRole::VERSION}"; exit
    when '-r', '--roles'; roles_dir = arg
    when '-G', '--no-git-ignore'; git_ignore = true
  end
}

args.size <= 1 or ShellOpts.error "Illegal number of arguments"
args.size != 0 or args << "make-roles"
make_roles_dir = args.first
File.directory?(make_roles_dir) or ShellOpts.error "Not a directory - #{make_roles_dir}"

if roles_dir
  begin
    FileUtils.mkdir_p(roles_dir)
  rescue SystemCallError
    ShellOpts.error "Can't create directory #{roles_dir}"
  end
else
  roles_dir = "#{File.dirname(make_roles_dir)}/roles"
  File.directory?(roles_dir) or ShellOpts.error "Can't find roles directory"
end





#for source in args
# File.directory?(source) or ShellOpts.error "Not a directory: #{source.inspect}"
# AnsibleMakeRole.make(source, verbose: verbose, force: force)
#end
