#!/usr/bin/env ruby

require 'ansible_make_role.rb'
require "shellopts"

USAGE = "f,force v,verbose version -- DIRECTORY..."

force = false
verbose = false

args = ShellOpts.process(USAGE, ARGV) { |opt, arg|
  case opt
    when '-f', '--force'; force = true
    when '-v', '--verbose'; verbose = true
    when '--version'; puts "ansible-make-role #{AnsibleMakeRole::VERSION}"; exit
  end
}
args.size > 0 or args << "."

for source in args
  begin
    AnsibleMakeRole.make(source, verbose: verbose, force: force)
  rescue AnsibleMakeRole::CantReadFile => ex
    ShellOpts::error("Can't read file #{ex.message}")
  rescue AnsibleMakeRole::CantWriteDir => ex
    ShellOpts::error("Can't write to directory #{ex.message}")
  end
end
